import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { LOCATIONS, BASE_URL, clinicNodes } from '@/lib/locations';

export default function LocaisAtendimento() {
  return <div className="theme-obsidian min-h-screen bg-background text-foreground"><Helmet><title>Locais de atendimento em Paragominas e Belém | Dr. Juliano Machado</title><meta name="description" content="Endereços e mapas dos locais de atendimento do Dr. Juliano Machado em Paragominas e Belém. Veja como agendar em cada cidade." /><link rel="canonical" href={BASE_URL+'/locais-de-atendimento'} /><meta name="robots" content="index, follow" /><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@graph':clinicNodes()})}</script></Helmet><Header />
    <main className="container max-w-5xl mx-auto px-5 pt-32 pb-20"><h1 className="font-serif text-4xl md:text-5xl mb-5">Locais de atendimento</h1><p className="text-muted-foreground text-lg max-w-3xl mb-10">Confira os endereços em Paragominas e Belém. A disponibilidade depende da unidade e do tipo de atendimento; confirme o local ao agendar.</p><div className="grid md:grid-cols-2 gap-6">{LOCATIONS.map(l => <section key={l.slug} className="rounded-xl border border-border bg-card p-6"><p className="text-sm text-primary mb-2">{l.city}</p><h2 className="font-serif text-2xl mb-4">{l.name}</h2><p className="text-muted-foreground mb-3">{l.displayAddress}<br />CEP {l.postalCode}</p><a href={'tel:'+l.phoneE164} className="text-primary underline">{l.phone}</a><div className="mt-5 flex flex-wrap gap-3"><a href={l.mapsLink} target="_blank" rel="noopener noreferrer" className="inline-flex items-center min-h-11 rounded-lg border border-border px-4">Abrir mapa</a><Link to={l.city==='Paragominas'?'/agendamento':'/belem'} className="inline-flex items-center min-h-11 rounded-lg bg-primary text-primary-foreground px-4">{l.city==='Paragominas'?'Ver disponibilidade':'Como agendar em Belém'}</Link></div></section>)}</div><div className="mt-10 flex flex-wrap gap-5"><Link to="/paragominas" className="text-primary underline">Oftalmologista em Paragominas</Link><Link to="/belem" className="text-primary underline">Atendimento em Belém</Link></div></main><Footer /></div>;
}
